theme: jekyll-theme-leap-day
title: ![Image](https://www.yeditepe.edu.tr/sites/default/files/logotryeditepe.png) Tıbbi Görüntüleme Laboratuvarı
description: Yeditepe Üniversitesi Biyomedikal Mühendisliği
